### ISSUE TITLE
store all dingo related files in .dingo dir instead of project root

### ISSUE THREAD

**Issue by ujinjinjin** [Ujinjinjin/dingo#46]

**Comment by ujinjinjin** [comment]
and maybe add config profiles. E.g.:

```yml
- default_profile: dev-stage
- dev-stage:
  - config_1: value_1
  - config_2: value_2
- prod-stage:
  - config_1: value_1
  - config_2: value_2
```
