### ISSUE TITLE
as a user I want to have config profiles

### ISSUE THREAD

**Issue by ujinjinjin** [Ujinjinjin/dingo#47]
Want to have single configuration file for different profiles.  E.g.:

```yml
- default_profile: dev-stage
- dev-stage:
  - config_1: value_1
  - config_2: value_2
- prod-stage:
  - config_1: value_1
  - config_2: value_2
```
